# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: pm2 restart api

    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.PK }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.PK}} | sed 's/./& /g' 
      # Use a GitHub Actions secret variable in a bash shell
      - name: Step 2 - GitHub Action if statement (true)
        env: 
          PK: ${{ secrets.PK }}
        if:  env.WHO_TO_TRUST == 'TrustNo1'
        run: echo "I know what the secret token is!"

      # A GitHub Actions if statement with a secret environment variable
      - name: Step 3 - Conditional GitHub Action (false)
        shell: bash
        env: 
          PK: ${{ secrets.PK }}
        if:  env.PK != 'TrustNobody'
        run: echo "I was wrong thinking the GitHub secret was 'TrustNobody'!"

